PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS webhooks (
    id         TEXT    PRIMARY KEY,                          -- UUID (e.g. generated by the app layer)
    name       TEXT    NOT NULL UNIQUE,
    url        TEXT    NOT NULL UNIQUE,
    status     TEXT    NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'paused')),
    created_at TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS event_types (
    id         TEXT    PRIMARY KEY,
    webhook_id TEXT    NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,  -- tied to a webhook
    name       TEXT    NOT NULL UNIQUE,
    UNIQUE (webhook_id, name)                               -- name unique per webhook, not globally
);

CREATE TABLE IF NOT EXISTS events (
    id              TEXT    PRIMARY KEY,
    webhook_id      TEXT    NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,
    event_type_id   TEXT    NOT NULL REFERENCES event_types(id),
    status          TEXT    NOT NULL DEFAULT 'sending' CHECK (status IN ('sending', 'success', 'fail')),
    timestamp       TEXT    NOT NULL,
    duration_ms     INTEGER NOT NULL DEFAULT 0,
    attempts        INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS deliveries (
    id          TEXT    PRIMARY KEY,
    event_id    TEXT    NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    webhook_id  TEXT    NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,
    status_code INTEGER NOT NULL,
    success     INTEGER NOT NULL DEFAULT 1 CHECK (success IN (0, 1)),
    duration_ms INTEGER NOT NULL DEFAULT 0,
    timestamp   TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS logs (
    id         TEXT    PRIMARY KEY,
    webhook_id TEXT    REFERENCES webhooks(id) ON DELETE SET NULL,
    level      TEXT    NOT NULL CHECK (level IN ('debug', 'info', 'warn', 'error')),
    message    TEXT    NOT NULL,
    timestamp  TEXT    NOT NULL
);

-- Settings are now per event_type rather than a single global row
CREATE TABLE IF NOT EXISTS settings (
    id              TEXT    PRIMARY KEY,
    event_type_id   TEXT NOT NULL UNIQUE REFERENCES event_types(id) ON DELETE CASCADE,
    retry_attempts  INTEGER NOT NULL DEFAULT 3,
    timeout_seconds INTEGER NOT NULL DEFAULT 30,
    enabled         INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))
);


CREATE INDEX IF NOT EXISTS idx_event_types_webhook_id ON event_types(webhook_id);

CREATE INDEX IF NOT EXISTS idx_events_webhook_id    ON events(webhook_id);
CREATE INDEX IF NOT EXISTS idx_events_event_type_id ON events(event_type_id);
CREATE INDEX IF NOT EXISTS idx_events_timestamp      ON events(timestamp);
CREATE INDEX IF NOT EXISTS idx_events_status         ON events(status);

CREATE INDEX IF NOT EXISTS idx_deliveries_event_id   ON deliveries(event_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_webhook_id ON deliveries(webhook_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_timestamp  ON deliveries(timestamp);

CREATE INDEX IF NOT EXISTS idx_logs_webhook_id ON logs(webhook_id);
CREATE INDEX IF NOT EXISTS idx_logs_timestamp  ON logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_logs_level      ON logs(level);

CREATE INDEX IF NOT EXISTS idx_webhooks_status ON webhooks(status);

CREATE INDEX IF NOT EXISTS idx_settings_event_type_id ON settings(event_type_id);
